### ISSUE TITLE
make it private please

### ISSUE THREAD

**Issue by joshianirudh** [SammithSB/6th-sem#1]

**Comment by ArvindAROO** [comment]
Ok, Sir

**Comment by Shamanthkolegodu** [comment]
Okay Unkil

**Comment by Abhijit-Sethi** [comment]
Aaytu Guruuuuu

**Comment by SathvikRao** [comment]
![WhatsApp Image 2022-05-06 at 9 37 17 AM](https://user-images.githubusercontent.com/56763200/167065461-4f2aade6-e3a4-4ce8-ab35-6c8940d6f61a.jpeg)

**Comment by abaksy** [comment]
Thandaani naane thanithandaano
Taane naane no
Thandaani naane thanithandaano
Taane naane no

**Comment by aditeyabaral** [comment]
I don't think GitHub comes up in plagiarism checking, they only check internally within submissions ~if they check at all~

**Comment by LawJarp-A** [comment]
Anyways we are failing only

**Comment by AlcorInf** [comment]
Okay bosssssssuuuuuuuuu

**Comment by 404-P4rziv4L** [comment]
![image](https://user-images.githubusercontent.com/57059194/167073707-3935ddad-b305-41ff-90ca-cd29c09d84d5.png)

**Comment by aditeyabaral** [comment]
![CatCuteGIF](https://user-images.githubusercontent.com/33230959/167074173-81e9543d-3fb8-40d3-adf0-b15a5ccdd207.gif)

**Comment by LaRuim** [comment]
oonts oonts

**Comment by karthik-sairam** [comment]
go watch MoM why CD project and all thu

**Comment by roysti10** [comment]
![image](https://user-images.githubusercontent.com/54945757/167148878-b175ad1f-ec96-482e-931b-8f839e597884.png)

**Comment by aditeyabaral** [comment]
![PugliePugliePugGIF](https://user-images.githubusercontent.com/33230959/167150106-0b1dab5a-a425-4e22-b906-c3c410c34c3e.gif)

**Comment by ArvindAROO** [comment]
"Its over"

**Comment by SammithSB** [comment]
its not you, its me

**Comment by aditeyabaral** [comment]
I wish it did not have to be this way

**Comment by abaksy** [comment]
"I wish it did not have to be this way" is what project evaluators will say before giving 0 marks for all projects

**Comment by SammithSB** [comment]
"you will always have a special place in my heart" is what 599  people will tell me after getting 0

**Comment by aditeyabaral** [comment]
@abaksy I do believe that empathy as a concept does not exist here

**Comment by SammithSB** [comment]
@abaksy should know that after what he did during MI lab

**Comment by joshianirudh** [comment]
Lmao

**Comment by joshianirudh** [comment]
> Okay Unkil

![image](https://user-images.githubusercontent.com/75616072/167176485-4323b891-7150-44ba-bd53-e7522458c929.png)

**Comment by joshianirudh** [comment]
This becoming an international conflict
* Me a github noob just trying to trigger ppl*
![image](https://user-images.githubusercontent.com/75616072/167177087-310f0e69-dd49-4741-b7a4-73d3f35c1531.png)
